apiVersion: v1
kind: Service
metadata:
  name: todos-rproxy-svc
  namespace: todos-ns
spec:
  type: ClusterIP
  selector:
    app: todos-rproxy
  ports:
    - port: 2348
      protocol: TCP
      targetPort: 80

