apiVersion: v1
kind: Service
metadata:
  name: ping-pong-lb-svc
spec:
  type: LoadBalancer # This should be the only unfamiliar part
  selector:
    app: ping-pong-deploy
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080

