# just for testing purpouses
#kind: # https://kubernetes.io/docs/concepts/workloads/controllers/job/
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
  namespace: ping-pong-ns
  labels:
    app: myjob
spec:
  template:
    metadata:
      name: myjob
      labels:
        app: myjob
    spec:
      containers:
        - name: postgresql-db
          image: k3d-myregistry.localhost:12345/postgres:14.3-alpine3.16
          ports:
            - name: pg-ss-port
              containerPort: 5432
          env:
          # - name: POSTGRES_PASSWORD
            # value: postgres
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: PG_PASSWORD
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
  
