apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-nats
  namespace: todos-ns
spec:
  interval: 5m
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats-helm-repo
        namespace: todos-ns
      interval: 1m

