apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: be
          image: k3d-myregistry.localhost:12345/project-be
          env:
          - name: GO_PORT
            value: "8080"
          - name: GIN_MODE
            value: "release"
