apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todos-be-hpa
  namespace: todos-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todos-be
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: "250Mi"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60

