apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - be-deploy.yaml
  - be-svc.yaml 
  - fe-deploy.yaml
  - fe-svc.yaml 
  - ing.yaml 
  - rproxy-deploy.yaml        
  - rproxy-svc.yaml 
  - secret.yaml 
  - h-be-autoscaler.yaml
images:
  - name: BE_IMAGE
    newName: BE_IMAGE
  - name: BE_DB_MIGRATIONS_IMAGE
    newName: BE_DB_MIGRATIONS_IMAGE
  - name: FE_IMAGE
    newName: FE_IMAGE
  - name: RPROXY_IMAGE
    newName: RPROXY_IMAGE
namespace: todos-ns

