name: GKE deletes branch ns
on: delete

jobs:
  deletes-branch:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - run: gcloud components install kubectl

    - name: gcp service account auth
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - run: gcloud container clusters get-credentials ${{ vars.GKE_CLUSTER }} --zone ${{ vars.GCP_ZONE }}
   
    - name: Get K8S namespace name
      id: k8s-ns-name
      run: |
        BRANCH_NAME="${{ github.event.ref}}" # this is not the same attrib used on full-deploy action. so can we use this instead?
        echo "branch name: $BRANCH_NAME"
        if [ "$BRANCH_NAME" == "main" ]; then
          echo "ns=todos-ns" >> $GITHUB_OUTPUT
        else
          echo "ns=todos-"$BRANCH_NAME"-ns" >> $GITHUB_OUTPUT
        fi

    - name: kubectl delete
      run: |-
        echo "deleting k8s ns: ${{ steps.k8s-ns-name.outputs.ns }}"
        kubectl delete namespace ${{ steps.k8s-ns-name.outputs.ns }}

